# Generated by Django 4.1.4 on 2023-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="regdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("mob", models.IntegerField(blank=True, max_length=100, null=True)),
                ("pas", models.CharField(blank=True, max_length=100, null=True)),
                ("passwd", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
